name: Output Context
on: workflow_dispatch
jobs:
    print-context:
        runs-on: ubuntu-latest
        steps:
            - name: Print Context
              run: echo "${{toJson(github)}}"
        
